import { createFileRoute, Link, useParams } from "@tanstack/react-router";
import { ArrowRight, Check, Globe2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { formatVerifiedDate, type BusinessProfile } from "@/lib/business-profile";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/verify/$verificationId")({ head: () => ({ meta: [{ title: "Domain Verified | BizVerify" }] }), component: PublicVerificationPage });

function PublicVerificationPage() {
  const { verificationId } = useParams({ from: "/verify/$verificationId" });
  const [profile, setProfile] = useState<BusinessProfile | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { supabase.from("business_profiles").select("*").eq("verification_id", verificationId).eq("verification_status", "verified").maybeSingle().then(({ data }) => { setProfile(data as BusinessProfile | null); setLoading(false); }); }, [verificationId]);
  if (loading) return <main className="grid min-h-screen place-items-center bg-background p-6 text-sm text-muted-foreground">Loading verification profile...</main>;
  if (!profile) return <main className="grid min-h-screen place-items-center bg-background p-6"><div className="max-w-md rounded-lg border border-border bg-surface p-8 text-center shadow-sm"><ShieldCheck className="mx-auto text-muted-foreground" size={38} /><h1 className="mt-4 text-2xl font-bold text-navy">Verification profile not found</h1><p className="mt-2 text-sm text-muted-foreground">This profile may not be verified or the link is no longer active.</p><Link to="/" className="mt-6 inline-flex rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Go to BizVerify</Link></div></main>;
  return <main className="min-h-screen bg-background px-5 py-10 text-foreground sm:py-16"><div className="mx-auto max-w-3xl"><Link to="/" className="flex items-center gap-2 font-bold text-navy"><span className="grid size-9 place-items-center rounded-md bg-primary text-primary-foreground"><ShieldCheck size={20} /></span>BizVerify</Link><section className="mt-10 overflow-hidden rounded-xl border border-border bg-surface shadow-sm"><div className="bg-navy px-6 py-10 text-white sm:px-10"><div className="flex items-start gap-4"><div className="grid size-12 place-items-center rounded-full bg-success text-white"><Check size={27} /></div><div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-cyan-200">Verified by BizVerify</p><h1 className="mt-2 text-3xl font-bold">Domain Verified</h1><p className="mt-2 text-sm text-slate-300">BizVerify verified control of this domain through a DNS TXT record.</p></div></div></div><div className="p-6 sm:p-10"><div className="flex flex-wrap items-center gap-4 border-b border-border pb-7"><div className="grid size-16 place-items-center overflow-hidden rounded-lg bg-accent text-primary">{profile.logo_url ? <img src={profile.logo_url} alt="" className="size-full object-cover" /> : <ShieldCheck size={29} />}</div><div><h2 className="text-2xl font-bold text-navy">{profile.brand_name || "Verified business"}</h2><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Globe2 size={15} />{profile.domain}</p></div></div><div className="mt-7 grid gap-6 sm:grid-cols-2"><Detail label="Domain" value={profile.domain} /><Detail label="Verification Status" value="Verified" /><Detail label="Verification Date" value={formatVerifiedDate(profile.verified_at)} /><Detail label="Verification ID" value={profile.verification_id} /><Detail label="Business/Brand Name" value={profile.brand_name || "Not provided" } /><Detail label="Website" value={profile.domain} /></div>{profile.description && <p className="mt-7 border-t border-border pt-6 text-sm leading-7 text-muted-foreground">{profile.description}</p>}<a href={profile.domain.startsWith("http") ? profile.domain : `https://${profile.domain}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Visit Website <ArrowRight size={15} /></a><p className="mt-8 text-xs leading-5 text-muted-foreground">BizVerify confirms domain ownership and verification status. It does not represent a guarantee of the business's legal legitimacy, quality, or conduct.</p></div></section></div></main>;
}

function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 wrap-break-word text-sm font-semibold text-navy">{value}</p></div>; }