import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, ClipboardCheck, Copy, ExternalLink, FileBadge2, Globe2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { EmptyProfileNotice, PageHeader, StatusPill, useDashboard } from "../dashboard";
import { formatVerifiedDate, profileUrl } from "@/lib/business-profile";

export const Route = createFileRoute("/dashboard/")({ component: DashboardHome });

function DashboardHome() {
  const { profile, userEmail, isLoading } = useDashboard();
  const [copied, setCopied] = useState(false);
  if (isLoading) return <LoadingState />;
  if (!profile) return <EmptyProfileNotice />;
  const displayName = profile.brand_name || "your business";
  const publicUrl = profileUrl(profile.verification_id);
  async function copyLink() { await navigator.clipboard.writeText(publicUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  return <div>
    <PageHeader eyebrow="Workspace" title={`Welcome back, ${displayName}`} description="Manage your domain verification, public profile and BizVerify badge." />
    <div className="grid gap-6 xl:grid-cols-[1.35fr_0.85fr]">
      <section className="rounded-lg border border-border bg-surface p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Verification status</p><h2 className="mt-2 text-xl font-bold text-navy">Domain Verification</h2><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><Globe2 size={15} />{profile.domain || "Add your domain to get started"}</p></div><StatusPill status={profile.verification_status} /></div>{profile.verification_status === "verified" ? <div className="mt-7 grid gap-4 border-t border-border pt-5 sm:grid-cols-3"><Detail label="Verification Method" value={profile.verification_method} /><Detail label="Verified On" value={formatVerifiedDate(profile.verified_at)} /><Detail label="Verification ID" value={profile.verification_id} /></div> : <div className="mt-6 border-t border-border pt-5"><p className="text-sm leading-6 text-muted-foreground">{profile.verification_status === "pending" ? "Complete the DNS verification setup and check your domain again." : "Verify your domain to activate your BizVerify public profile and trust badge."}</p></div>}<div className="mt-6 flex flex-wrap gap-3">{profile.verification_status === "verified" && <Link to="/verify/$verificationId" params={{ verificationId: profile.verification_id }} className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2.5 text-sm font-semibold text-navy hover:bg-accent">View Public Profile <ExternalLink size={15} /></Link>}<Link to="/dashboard/verification" className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">{profile.verification_status === "verified" ? "Manage Verification" : "Verify Domain"}<ArrowRight size={15} /></Link></div></section>
      <section className="rounded-lg border border-border bg-surface p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Public profile</p><h2 className="mt-2 text-xl font-bold text-navy">Your Public Verification Profile</h2><div className="mt-5 flex items-center gap-3"><div className="grid size-12 place-items-center overflow-hidden rounded-md bg-accent text-primary">{profile.logo_url ? <img src={profile.logo_url} alt="" className="size-full object-cover" /> : <ShieldCheck size={22} />}</div><div><p className="font-semibold text-navy">{displayName}</p><p className="text-sm text-muted-foreground">{profile.domain || "Domain not added"}</p></div></div><div className="mt-5 space-y-3 border-t border-border pt-5"><div className="flex items-center justify-between gap-3 text-sm"><span className="text-muted-foreground">Status</span><StatusPill status={profile.verification_status} /></div><Detail label="Verification ID" value={profile.verification_id} /></div><p className="mt-5 truncate rounded-md bg-muted px-3 py-2 text-xs text-muted-foreground">{publicUrl.replace(/^https?:\/\//, "")}</p><div className="mt-4 flex flex-wrap gap-3"><Link to="/dashboard/profile" className="text-sm font-semibold text-primary hover:underline">View profile</Link><button type="button" onClick={copyLink} className="inline-flex items-center gap-1.5 text-sm font-semibold text-muted-foreground hover:text-foreground"><Copy size={14} />{copied ? "Copied" : "Copy link"}</button></div></section>
    </div>
    <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Quick actions</p><h2 className="mt-1 text-xl font-bold text-navy">Keep your trust profile moving</h2></div></div><div className="grid gap-4 md:grid-cols-3"><ActionCard icon={ClipboardCheck} title="Verify Domain" text="Verify your website ownership using DNS." to="/dashboard/verification" action="Verify Domain" /><ActionCard icon={ExternalLink} title="Public Profile" text="Manage the information visitors see when they verify your website." to="/dashboard/profile" action="Manage Profile" /><ActionCard icon={FileBadge2} title="Trust Badge" text="Add the BizVerify verification badge to your website." to="/dashboard/badge" action="Get Badge" /></div></section>
  </div>;
}

function ActionCard({ icon: Icon, title, text, to, action }: { icon: typeof ClipboardCheck; title: string; text: string; to: "/dashboard/verification" | "/dashboard/profile" | "/dashboard/badge"; action: string }) { return <div className="rounded-lg border border-border bg-surface p-5 shadow-sm"><div className="grid size-10 place-items-center rounded-md bg-accent text-primary"><Icon size={19} /></div><h3 className="mt-4 font-bold text-navy">{title}</h3><p className="mt-2 min-h-10 text-sm leading-5 text-muted-foreground">{text}</p><Link to={to} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary">{action}<ArrowRight size={15} /></Link></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 wrap-break-word text-sm font-semibold text-navy">{value}</p></div>; }
function LoadingState() { return <div className="rounded-lg border border-border bg-surface p-10 text-center text-sm text-muted-foreground">Loading your workspace...</div>; }