import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { LogOut, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { PageHeader, ProfileUnavailableNotice, useDashboard } from "../dashboard";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/dashboard/settings")({ component: SettingsPage });

function SettingsPage() {
  const { profile, userEmail, refreshProfile, isLoading } = useDashboard();
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [notifications, setNotifications] = useState(true);
  const [message, setMessage] = useState("");
  if (isLoading) return <div className="rounded-lg border border-border bg-surface p-10 text-center text-sm text-muted-foreground">Loading account settings...</div>;
  if (!profile) return <ProfileUnavailableNotice />;
  async function saveAccount() { const result = await supabase.from("business_profiles").update({ brand_name: name || profile.brand_name, email_notifications: notifications }).eq("id", profile.id); if (result.error) { setMessage(result.error.message); return; } if (password) { const passwordResult = await supabase.auth.updateUser({ password }); if (passwordResult.error) { setMessage(passwordResult.error.message); return; } setPassword(""); } await refreshProfile(); setMessage("Account settings saved."); }
  async function logout() { if (!window.confirm("Are you sure you want to log out?")) return; await supabase.auth.signOut(); await navigate({ to: "/" }); }
  async function deleteAccount() { if (!window.confirm("Are you sure you want to delete your account? This cannot be undone.")) return; const result = await supabase.rpc("delete_my_account"); if (result.error) { setMessage(result.error.message); return; } await supabase.auth.signOut(); await navigate({ to: "/" }); }
  return <div><PageHeader eyebrow="Account" title="Account Settings" description="Manage your account access, password, and notification preferences." /><div className="grid max-w-4xl gap-6"><section className="rounded-lg border border-border bg-surface p-6 shadow-sm"><h2 className="text-lg font-bold text-navy">Account Information</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="block text-sm font-semibold text-navy">Name<input value={name || profile.brand_name} onChange={(event) => setName(event.target.value)} className="mt-2 block w-full rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></label><label className="block text-sm font-semibold text-navy">Email<input value={userEmail} readOnly className="mt-2 block w-full rounded-md border border-input bg-muted px-3 py-3 text-muted-foreground outline-none" /></label></div></section><section className="rounded-lg border border-border bg-surface p-6 shadow-sm"><h2 className="text-lg font-bold text-navy">Security</h2><label className="mt-5 block max-w-md text-sm font-semibold text-navy">Change Password<input type="password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter a new password" className="mt-2 block w-full rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></label></section><section className="rounded-lg border border-border bg-surface p-6 shadow-sm"><h2 className="text-lg font-bold text-navy">Notifications</h2><label className="mt-5 flex max-w-md items-center justify-between gap-4 text-sm font-semibold text-navy">Email Notifications<input type="checkbox" checked={notifications} onChange={(event) => setNotifications(event.target.checked)} className="size-5 accent-primary" /></label></section><section className="rounded-lg border border-border bg-surface p-6 shadow-sm"><h2 className="text-lg font-bold text-navy">Account</h2><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={saveAccount} className="rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Save Settings</button><button type="button" onClick={logout} className="inline-flex items-center gap-2 rounded-md border border-border px-4 py-2.5 text-sm font-semibold text-navy"><LogOut size={15} />Logout</button><button type="button" onClick={deleteAccount} className="rounded-md border border-destructive/30 px-4 py-2.5 text-sm font-semibold text-destructive">Delete Account</button></div>{message && <p className="mt-4 text-sm text-muted-foreground">{message}</p>}</section><div className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck size={15} />Your password is handled securely by Supabase Auth.</div></div></div>;
}